// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/android/incallui/callconfiguration/call_configuration.proto

package com.wintmain.dialer;

public interface CallConfigurationOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.wintmain.dialer.CallConfiguration)
        com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .com.wintmain.dialer.Mode call_mode = 1;</code>
     */
    boolean hasCallMode();

    /**
     * <code>optional .com.wintmain.dialer.Mode call_mode = 1;</code>
     */
    com.wintmain.dialer.Mode getCallMode();
}
