// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/wintmain/dialer/phonenumberproto/dialer_phone_number.proto

package com.wintmain.dialer;

public final class DialerPhoneNumberOuterClass {

    private DialerPhoneNumberOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
