// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/wintmain/dialer/calllog/database/contract/number_attributes.proto

package com.wintmain.dialer;

public final class NumberAttributesOuterClass {

    private NumberAttributesOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
