// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packages/apps/Dialer/java/com/fissy/dialer/dialercontact/dialer_contact.proto

package com.wintmain.dialer.dialercontact;

public final class DialerContactOuterClass {

    private DialerContactOuterClass() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
